/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.Idioma;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author KEVIN
 */
public class interfazIdioma extends javax.swing.JFrame {
    
    Idioma back_endIdioma;
    /**
     * Creates new form interfazIdioma
     */
    public interfazIdioma() {
        initComponents();
        back_endIdioma = new Idioma();
        //botones
        btn_deleteIdioma.setVisible(false);
        btn_insertIdioma.setVisible(false);
        btn_limpiarCampos.setVisible(false);
        btn_searchIdioma.setVisible(false);
        btn_showIidoma.setVisible(false);
        btn_updateIdioma.setVisible(false);
        //tabla
        Table_idiomaData.setVisible(false);
        //combo
        CB_setIdioma.setVisible(false);
        //textfield
        Txt_busquedaInput.setVisible(false);
        Txt_idioma.setEnabled(false);
        Txt_idIdioma.setEnabled(false);
        Txt_LugarIidoma.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Txt_idIdioma = new javax.swing.JTextField();
        Txt_idioma = new javax.swing.JTextField();
        btn_insertIdioma = new javax.swing.JButton();
        btn_limpiarCampos = new javax.swing.JButton();
        btn_showIidoma = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Txt_LugarIidoma = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_idiomaData = new javax.swing.JTable();
        CB_setIdioma = new javax.swing.JComboBox<>();
        Txt_busquedaInput = new javax.swing.JTextField();
        btn_searchIdioma = new javax.swing.JButton();
        btn_deleteIdioma = new javax.swing.JButton();
        btn_updateIdioma = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Menu_nuevoIdioma = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Menu_buscarIdioma = new javax.swing.JMenuItem();
        Menu_eliminarIdioma = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Informacion Idioma");

        jLabel2.setText("Id Idioma");

        jLabel3.setText("Idioma");

        btn_insertIdioma.setText("Insertar");
        btn_insertIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertIdiomaActionPerformed(evt);
            }
        });

        btn_limpiarCampos.setText("Limpiar");
        btn_limpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarCamposActionPerformed(evt);
            }
        });

        btn_showIidoma.setText("Mostrar Datos");
        btn_showIidoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showIidomaActionPerformed(evt);
            }
        });

        jLabel4.setText("Lugar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(Txt_idIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(Txt_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Txt_LugarIidoma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btn_insertIdioma)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_limpiarCampos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_showIidoma))))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_idIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Txt_LugarIidoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_insertIdioma)
                    .addComponent(btn_limpiarCampos)
                    .addComponent(btn_showIidoma))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Table_idiomaData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Table_idiomaData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_idiomaDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_idiomaData);

        CB_setIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Idioma" }));

        btn_searchIdioma.setText("Buscar");
        btn_searchIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchIdiomaActionPerformed(evt);
            }
        });

        btn_deleteIdioma.setText("Eliminar");
        btn_deleteIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteIdiomaActionPerformed(evt);
            }
        });

        btn_updateIdioma.setText("Actualizar");
        btn_updateIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateIdiomaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CB_setIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_deleteIdioma)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Txt_busquedaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_searchIdioma))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_updateIdioma)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_setIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_busquedaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_searchIdioma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_deleteIdioma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_updateIdioma)
                .addGap(28, 28, 28))
        );

        jMenu1.setText("File");

        Menu_nuevoIdioma.setText("Nuevo Idioma");
        Menu_nuevoIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_nuevoIdiomaActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_nuevoIdioma);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        Menu_buscarIdioma.setText("Buscar Idioma");
        Menu_buscarIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_buscarIdiomaActionPerformed(evt);
            }
        });
        jMenu2.add(Menu_buscarIdioma);

        Menu_eliminarIdioma.setText("Eliminar Idioma");
        Menu_eliminarIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_eliminarIdiomaActionPerformed(evt);
            }
        });
        jMenu2.add(Menu_eliminarIdioma);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertIdiomaActionPerformed
        try {
            // TODO add your handling code here:
            back_endIdioma.insertIdioma(Integer.parseInt(Txt_idIdioma.getText()), Txt_idioma.getText(),Txt_LugarIidoma.getText());
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(interfazIdioma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_insertIdiomaActionPerformed

    private void btn_limpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarCamposActionPerformed
        // TODO add your handling code here:
        Txt_idIdioma.setText("");
        Txt_idioma.setText("");
        Txt_LugarIidoma.setText("");
    }//GEN-LAST:event_btn_limpiarCamposActionPerformed

    private void btn_showIidomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showIidomaActionPerformed
        try {
            // TODO add your handling code here:
            back_endIdioma.MostrarDataIdioma(Table_idiomaData);
        } catch (SQLException ex) {
            Logger.getLogger(interfazIdioma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_showIidomaActionPerformed

    private void btn_searchIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchIdiomaActionPerformed
        try {
            // TODO add your handling code here:
            back_endIdioma.buscarIdioma(CB_setIdioma.getItemAt(CB_setIdioma.getSelectedIndex()), Table_idiomaData, Txt_busquedaInput.getText());
        } catch (SQLException ex) {
            Logger.getLogger(interfazIdioma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_searchIdiomaActionPerformed

    private void btn_deleteIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteIdiomaActionPerformed
        try {
            // TODO add your handling code here:
            back_endIdioma.deleteIdioma(CB_setIdioma.getItemAt(CB_setIdioma.getSelectedIndex()), Txt_busquedaInput.getText());
        } catch (SQLException ex) {
            Logger.getLogger(interfazIdioma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_deleteIdiomaActionPerformed
        
    private void Table_idiomaDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_idiomaDataMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==2) {
            Txt_idIdioma.setText("");
            Txt_idioma.setText("");    
            Txt_LugarIidoma.setText("");
            
        //botones
            btn_deleteIdioma.setVisible(false);
            btn_insertIdioma.setVisible(false);
            btn_limpiarCampos.setVisible(false);
            btn_searchIdioma.setVisible(true);
            btn_showIidoma.setVisible(true);
            btn_updateIdioma.setVisible(true);
        //tabla
            Table_idiomaData.setVisible(true);
        //combo
            CB_setIdioma.setVisible(true);
        //textfield
            Txt_busquedaInput.setVisible(true);
            Txt_idioma.setEnabled(true);
            Txt_idIdioma.setEnabled(true);
            Txt_LugarIidoma.setEnabled(false);
                    
            for (int i = 0; i < Table_idiomaData.getRowCount(); i++) {
                Txt_idIdioma.setText(Table_idiomaData.getValueAt(i, 0).toString());
                Txt_idioma.setText(Table_idiomaData.getValueAt(i, 1).toString());      
                Txt_LugarIidoma.setText(Table_idiomaData.getValueAt(i, 2).toString());
            }
        }
    }//GEN-LAST:event_Table_idiomaDataMouseClicked

    private void btn_updateIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateIdiomaActionPerformed
        try {
            // TODO add your handling code here:
            back_endIdioma.updateIdioma(CB_setIdioma.getItemAt(CB_setIdioma.getSelectedIndex()), Txt_busquedaInput.getText(), Txt_idioma.getText());
        } catch (SQLException ex) {
            Logger.getLogger(interfazIdioma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_updateIdiomaActionPerformed

    private void Menu_nuevoIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_nuevoIdiomaActionPerformed
        // TODO add your handling code here:
        Txt_idIdioma.setText("");
        Txt_idioma.setText("");    
        Txt_busquedaInput.setText("");
        //botones
        btn_deleteIdioma.setVisible(false);
        btn_insertIdioma.setVisible(true);
        btn_limpiarCampos.setVisible(true);
        btn_searchIdioma.setVisible(false);
        btn_showIidoma.setVisible(true);
        btn_updateIdioma.setVisible(false);
        //tabla
        Table_idiomaData.setVisible(true);
        //combo
        CB_setIdioma.setVisible(false);
        //textfield
        Txt_busquedaInput.setVisible(false);
        Txt_idioma.setEnabled(true);
        Txt_idIdioma.setEnabled(true);
        Txt_LugarIidoma.setEnabled(true);
    
        
    }//GEN-LAST:event_Menu_nuevoIdiomaActionPerformed

    private void Menu_buscarIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_buscarIdiomaActionPerformed
        // TODO add your handling code here:
        Txt_idIdioma.setText("");
        Txt_idioma.setText("");
        Txt_busquedaInput.setText("");
        Txt_LugarIidoma.setText("");
        //botones
        btn_deleteIdioma.setVisible(false);
        btn_insertIdioma.setVisible(false);
        btn_limpiarCampos.setVisible(false);
        btn_searchIdioma.setVisible(true);
        btn_showIidoma.setVisible(false);
        btn_updateIdioma.setVisible(false);
        //tabla
        Table_idiomaData.setVisible(true);
        //combo
        CB_setIdioma.setVisible(true);
        //textfield
        Txt_busquedaInput.setVisible(true);
        Txt_idioma.setEnabled(false);
        Txt_idIdioma.setEnabled(false);
        Txt_LugarIidoma.setEnabled(false);
    
    }//GEN-LAST:event_Menu_buscarIdiomaActionPerformed

    private void Menu_eliminarIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_eliminarIdiomaActionPerformed
        // TODO add your handling code here:
        Txt_idIdioma.setText("");
        Txt_idioma.setText("");
        Txt_busquedaInput.setText("");
        Txt_LugarIidoma.setText("");
        //botones
        btn_deleteIdioma.setVisible(true);
        btn_insertIdioma.setVisible(false);
        btn_limpiarCampos.setVisible(false);
        btn_searchIdioma.setVisible(true);
        btn_showIidoma.setVisible(true);
        btn_updateIdioma.setVisible(false);
        //tabla
        Table_idiomaData.setVisible(true);
        //combo
        CB_setIdioma.setVisible(true);
        //textfield
        Txt_busquedaInput.setVisible(true);
        Txt_idioma.setEnabled(false);
        Txt_idIdioma.setEnabled(false);
        Txt_LugarIidoma.setEnabled(false);
    
    }//GEN-LAST:event_Menu_eliminarIdiomaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazIdioma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazIdioma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazIdioma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazIdioma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazIdioma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_setIdioma;
    private javax.swing.JMenuItem Menu_buscarIdioma;
    private javax.swing.JMenuItem Menu_eliminarIdioma;
    private javax.swing.JMenuItem Menu_nuevoIdioma;
    private javax.swing.JTable Table_idiomaData;
    private javax.swing.JTextField Txt_LugarIidoma;
    private javax.swing.JTextField Txt_busquedaInput;
    private javax.swing.JTextField Txt_idIdioma;
    private javax.swing.JTextField Txt_idioma;
    private javax.swing.JButton btn_deleteIdioma;
    private javax.swing.JButton btn_insertIdioma;
    private javax.swing.JButton btn_limpiarCampos;
    private javax.swing.JButton btn_searchIdioma;
    private javax.swing.JButton btn_showIidoma;
    private javax.swing.JButton btn_updateIdioma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
