/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.Genero;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author KEVIN
 */
public class interfazGenero extends javax.swing.JFrame {

    Genero back_endGenero;
    /**
     * Creates new form interfazGenero
     */
    public interfazGenero() {
        initComponents();
        back_endGenero=new Genero();
        //botones
        btn_clearCampos.setVisible(false);
        btn_deleteRecord.setVisible(false);
        btn_insertRecord.setVisible(false);
        btn_showData.setVisible(false);
        btn_searchRecord.setVisible(false);
        btn_updateRecord.setVisible(false);
        //tabla
        Table_generoData.setVisible(false);
        //combo
        CB_tipoBusqueda.setVisible(false);
        //textfiel
        Txt_entrada.setVisible(false);
        Txt_idGenero.setEnabled(false);
        Txt_tipoGenero.setEnabled(false);
        txtArea_descripcion.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_descripcion = new javax.swing.JTextArea();
        Txt_idGenero = new javax.swing.JTextField();
        Txt_tipoGenero = new javax.swing.JTextField();
        btn_insertRecord = new javax.swing.JButton();
        btn_clearCampos = new javax.swing.JButton();
        btn_showData = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_generoData = new javax.swing.JTable();
        CB_tipoBusqueda = new javax.swing.JComboBox<>();
        Txt_entrada = new javax.swing.JTextField();
        btn_searchRecord = new javax.swing.JButton();
        btn_deleteRecord = new javax.swing.JButton();
        btn_updateRecord = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Menu_nuevoGenero = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Menu_buscarGenero = new javax.swing.JMenuItem();
        Menu_eliminarGenero = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Informacion Genero");

        jLabel2.setText("Id Genero");

        jLabel3.setText("Tipo de Genero");

        jLabel4.setText("Descripcion");

        txtArea_descripcion.setColumns(20);
        txtArea_descripcion.setRows(5);
        jScrollPane1.setViewportView(txtArea_descripcion);

        btn_insertRecord.setText("Insertar");
        btn_insertRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertRecordActionPerformed(evt);
            }
        });

        btn_clearCampos.setText("Limpiar");
        btn_clearCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearCamposActionPerformed(evt);
            }
        });

        btn_showData.setText("Mostar Datos");
        btn_showData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Txt_idGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txt_tipoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_insertRecord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_clearCampos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_showData)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_idGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_tipoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_insertRecord)
                    .addComponent(btn_clearCampos)
                    .addComponent(btn_showData))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Table_generoData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Table_generoData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_generoDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table_generoData);

        CB_tipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genero", "Descripcion del Genero" }));

        btn_searchRecord.setText("Buscar");
        btn_searchRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchRecordActionPerformed(evt);
            }
        });

        btn_deleteRecord.setText("Eliminar");
        btn_deleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteRecordActionPerformed(evt);
            }
        });

        btn_updateRecord.setText("Actualizar");
        btn_updateRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateRecordActionPerformed(evt);
            }
        });

        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CB_tipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_deleteRecord)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Txt_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btn_searchRecord))))
                    .addComponent(btn_updateRecord)
                    .addComponent(btn_regresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_tipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_searchRecord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_deleteRecord)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_updateRecord)
                .addGap(18, 18, 18)
                .addComponent(btn_regresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        Menu_nuevoGenero.setText("Nuevo Genero");
        Menu_nuevoGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_nuevoGeneroActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_nuevoGenero);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        Menu_buscarGenero.setText("Buscar Genero");
        Menu_buscarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_buscarGeneroActionPerformed(evt);
            }
        });
        jMenu2.add(Menu_buscarGenero);

        Menu_eliminarGenero.setText("Eliminar Genero");
        Menu_eliminarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_eliminarGeneroActionPerformed(evt);
            }
        });
        jMenu2.add(Menu_eliminarGenero);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertRecordActionPerformed
        try {
            isNumber(Txt_idGenero.getText());
            if ((Txt_idGenero.getText().length()==0)||(Txt_tipoGenero.getText().length()==0)||(txtArea_descripcion.getText().length()==0)) {
                JOptionPane.showMessageDialog(null, "Falta de ingresar campos");
            }else{
                back_endGenero.insertGenero(Integer.parseInt(Txt_idGenero.getText()), Txt_tipoGenero.getText(), txtArea_descripcion.getText());
                Table_generoData.setVisible(false);
            }            
        } catch (SQLException | ParseException | NumberFormatException ex) {
            //Logger.getLogger(interfazGenero.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        } 
    }//GEN-LAST:event_btn_insertRecordActionPerformed

    private void btn_clearCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearCamposActionPerformed
        // TODO add your handling code here:
        Txt_idGenero.setText("");
        Txt_tipoGenero.setText("");
        txtArea_descripcion.setText("");
        Table_generoData.setVisible(false);
    }//GEN-LAST:event_btn_clearCamposActionPerformed

    private void btn_showDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showDataActionPerformed
        try {
            // TODO add your handling code here:
            back_endGenero.MostrarDataGenero(Table_generoData);
            Table_generoData.setVisible(true);
        } catch (SQLException ex) {
            //Logger.getLogger(interfazGenero.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btn_showDataActionPerformed

    private void btn_searchRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchRecordActionPerformed
        try {
            if (Txt_entrada.getText().length()==0) {
                JOptionPane.showMessageDialog(null, "Ingrese dato ha buscar");
            }else{
                back_endGenero.buscarGenero(CB_tipoBusqueda.getItemAt(CB_tipoBusqueda.getSelectedIndex()), Table_generoData, Txt_entrada.getText());
                Table_generoData.setVisible(true);
            }
            
        } catch (SQLException ex) {
            //Logger.getLogger(interfazGenero.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btn_searchRecordActionPerformed

    private void btn_deleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteRecordActionPerformed
        
        try {
            if (Txt_entrada.getText().length()==0) {
                JOptionPane.showMessageDialog(null, "Ingrese dato ha eliminar");
            }else{
                back_endGenero.deleteGenero(CB_tipoBusqueda.getItemAt(CB_tipoBusqueda.getSelectedIndex()), Txt_entrada.getText());
                btn_showData.setVisible(true);                 
            }
        } catch (SQLException ex) {
            //Logger.getLogger(interfazGenero.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btn_deleteRecordActionPerformed

    private void btn_updateRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateRecordActionPerformed
        try {
            // TODO add your handling code here:
            if ((Txt_entrada.getText().length()==0)||(Txt_idGenero.getText().length()==0)||(Txt_tipoGenero.getText().length()==0)||(txtArea_descripcion.getText().length()==0)) {
                JOptionPane.showMessageDialog(null, "Falta de ingresar datos");
            }else{
                back_endGenero.updateAlbum(CB_tipoBusqueda.getItemAt(CB_tipoBusqueda.getSelectedIndex()), Txt_entrada.getText(), Txt_tipoGenero.getText(),txtArea_descripcion.getText());               
                btn_showData.setVisible(true);
                Txt_entrada.setText("");
                Txt_idGenero.setText("");
                Txt_tipoGenero.setText("");
                txtArea_descripcion.setText("");
            }            
        } catch (SQLException ex) {
            //Logger.getLogger(interfazGenero.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btn_updateRecordActionPerformed

    private void Table_generoDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_generoDataMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==2) {            
        //botones
            btn_clearCampos.setVisible(false);
            btn_deleteRecord.setVisible(false);
            btn_insertRecord.setVisible(false);
            btn_showData.setVisible(false);
            btn_searchRecord.setVisible(true);
            btn_updateRecord.setVisible(true);
        //tabla
            Table_generoData.setVisible(false);
        //combo
            CB_tipoBusqueda.setVisible(true);
        //textfiel
            Txt_entrada.setVisible(true);
            Txt_idGenero.setEnabled(false);
            Txt_tipoGenero.setEnabled(true);
            txtArea_descripcion.setEnabled(true);
            for (int i = 0; i < Table_generoData.getRowCount(); i++) {
                Txt_idGenero.setText(Table_generoData.getValueAt(i, 0).toString());
                Txt_tipoGenero.setText(Table_generoData.getValueAt(i, 1).toString());
                txtArea_descripcion.setText(Table_generoData.getValueAt(i, 2).toString());
            }
            
        }
    }//GEN-LAST:event_Table_generoDataMouseClicked

    private void Menu_nuevoGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_nuevoGeneroActionPerformed
        // TODO add your handling code here:
        Txt_idGenero.setText("");
        Txt_tipoGenero.setText("");
        txtArea_descripcion.setText("");
        Txt_entrada.setText("");
        //botones
        btn_clearCampos.setVisible(true);
        btn_deleteRecord.setVisible(false);
        btn_insertRecord.setVisible(true);
        btn_showData.setVisible(true);
        btn_searchRecord.setVisible(false);
        btn_updateRecord.setVisible(false);
        //tabla
        Table_generoData.setVisible(false);
        //combo
        CB_tipoBusqueda.setVisible(false);
        //textfiel
        Txt_entrada.setVisible(false);
        Txt_idGenero.setEnabled(true);
        Txt_tipoGenero.setEnabled(true);
        txtArea_descripcion.setEnabled(true);
        
    }//GEN-LAST:event_Menu_nuevoGeneroActionPerformed

    private void Menu_buscarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_buscarGeneroActionPerformed
        // TODO add your handling code here:
        Txt_idGenero.setText("");
        Txt_tipoGenero.setText("");
        txtArea_descripcion.setText("");
        Txt_entrada.setText("");
        //botones
        btn_clearCampos.setVisible(false);
        btn_deleteRecord.setVisible(false);
        btn_insertRecord.setVisible(false);
        btn_showData.setVisible(false);
        btn_searchRecord.setVisible(true);
        btn_updateRecord.setVisible(false);
        //tabla
        Table_generoData.setVisible(false);
        //combo
        CB_tipoBusqueda.setVisible(true);
        //textfiel
        Txt_entrada.setVisible(true);
        Txt_idGenero.setEnabled(false);
        Txt_tipoGenero.setEnabled(false);
        txtArea_descripcion.setEnabled(false);
        
    }//GEN-LAST:event_Menu_buscarGeneroActionPerformed

    private void Menu_eliminarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_eliminarGeneroActionPerformed
        // TODO add your handling code here:
        Txt_idGenero.setText("");
        Txt_tipoGenero.setText("");
        txtArea_descripcion.setText("");
        Txt_entrada.setText("");
        //botones
        btn_clearCampos.setVisible(false);
        btn_deleteRecord.setVisible(true);
        btn_insertRecord.setVisible(false);
        btn_showData.setVisible(false);
        btn_searchRecord.setVisible(true);
        btn_updateRecord.setVisible(false);
        //tabla
        Table_generoData.setVisible(false);
        
        //combo
        CB_tipoBusqueda.setVisible(true);
        //textfiel
        Txt_entrada.setVisible(true);
        Txt_idGenero.setEnabled(false);
        Txt_tipoGenero.setEnabled(false);
        txtArea_descripcion.setEnabled(false);
    }//GEN-LAST:event_Menu_eliminarGeneroActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //new interfazPrincipal().setVisible(true);
    }//GEN-LAST:event_btn_regresarActionPerformed

    private static boolean isNumber(String id){
        try {
            Integer.parseInt(id);
            return true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
            return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazGenero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_tipoBusqueda;
    private javax.swing.JMenuItem Menu_buscarGenero;
    private javax.swing.JMenuItem Menu_eliminarGenero;
    private javax.swing.JMenuItem Menu_nuevoGenero;
    private javax.swing.JTable Table_generoData;
    private javax.swing.JTextField Txt_entrada;
    private javax.swing.JTextField Txt_idGenero;
    private javax.swing.JTextField Txt_tipoGenero;
    private javax.swing.JButton btn_clearCampos;
    private javax.swing.JButton btn_deleteRecord;
    private javax.swing.JButton btn_insertRecord;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JButton btn_searchRecord;
    private javax.swing.JButton btn_showData;
    private javax.swing.JButton btn_updateRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtArea_descripcion;
    // End of variables declaration//GEN-END:variables
}
