/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.Album;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author KEVIN
 */
public class interfazAlbum extends javax.swing.JFrame {
    Album backEnd_album;
    /**
     * Creates new form interfazAlbum
     */
    public interfazAlbum() {
        initComponents();
        backEnd_album = new Album();
        
        //botones
        Button_insertRecord.setVisible(false);
        Button_clearCampos.setVisible(false);
        Button_showData.setVisible(false);
        Button_deleteRecord.setVisible(false);
        Button_searchRecord.setVisible(false);
        Button_updateRecord.setVisible(false);
        //combo
        CB_options.setVisible(false);
        //tabla
        Table_dataAlbum.setVisible(false);
        //textfield
        Text_anioLan.setEnabled(false);
        Text_idAlbum.setEnabled(false);
        Text_idInterprete.setEnabled(false);
        Text_input.setVisible(false);
        Text_lugarGrabacion.setEnabled(false);
        Text_nameAlbum.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Text_idAlbum = new javax.swing.JTextField();
        Text_idInterprete = new javax.swing.JTextField();
        Text_nameAlbum = new javax.swing.JTextField();
        Text_lugarGrabacion = new javax.swing.JTextField();
        Text_anioLan = new javax.swing.JTextField();
        Button_insertRecord = new javax.swing.JButton();
        Button_clearCampos = new javax.swing.JButton();
        Button_showData = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CB_options = new javax.swing.JComboBox<>();
        Text_input = new javax.swing.JTextField();
        Button_searchRecord = new javax.swing.JButton();
        Button_deleteRecord = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_dataAlbum = new javax.swing.JTable();
        Button_updateRecord = new javax.swing.JButton();
        btn_regresarMain = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Menu_nuevoAlbum = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Menu_buscarAlbum = new javax.swing.JMenuItem();
        Menu_eliminarAlbum = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Datos del Album");

        jLabel2.setText("Id Album");

        jLabel3.setText("Id Inteprete");

        jLabel4.setText("Nombre Album");

        jLabel5.setText("Lugar de Grabacion");

        jLabel6.setText("Año de Lanzamiento");

        Button_insertRecord.setText("Agregar");
        Button_insertRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_insertRecordActionPerformed(evt);
            }
        });

        Button_clearCampos.setText("Limpiar");
        Button_clearCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_clearCamposActionPerformed(evt);
            }
        });

        Button_showData.setText("mostar datos");
        Button_showData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_showDataActionPerformed(evt);
            }
        });

        jLabel7.setText("DD-MMM-YYYY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Text_idAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Text_idInterprete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(Text_nameAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel5))
                            .addComponent(Text_lugarGrabacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Text_anioLan)
                            .addComponent(jLabel7))))
                .addGap(88, 88, 88))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_insertRecord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_clearCampos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_showData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Text_idAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Text_idInterprete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_nameAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text_lugarGrabacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text_anioLan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_insertRecord)
                    .addComponent(Button_clearCampos)
                    .addComponent(Button_showData))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        CB_options.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre Album", "Lugar Grabacion", "Año de Grabacion" }));

        Button_searchRecord.setText("Buscar");
        Button_searchRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_searchRecordActionPerformed(evt);
            }
        });

        Button_deleteRecord.setText("Eliminar");
        Button_deleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_deleteRecordActionPerformed(evt);
            }
        });

        Table_dataAlbum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Table_dataAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_dataAlbumMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_dataAlbum);

        Button_updateRecord.setText("Actualizar");
        Button_updateRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_updateRecordActionPerformed(evt);
            }
        });

        btn_regresarMain.setText("Regresar");
        btn_regresarMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(CB_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button_deleteRecord)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Text_input, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Button_searchRecord))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_updateRecord)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_regresarMain)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_searchRecord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_deleteRecord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_updateRecord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_regresarMain)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        Menu_nuevoAlbum.setText("Nuevo Album");
        Menu_nuevoAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_nuevoAlbumActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_nuevoAlbum);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        Menu_buscarAlbum.setText("Buscar Album");
        Menu_buscarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_buscarAlbumActionPerformed(evt);
            }
        });
        jMenu2.add(Menu_buscarAlbum);

        Menu_eliminarAlbum.setText("Eliminar Album");
        Menu_eliminarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_eliminarAlbumActionPerformed(evt);
            }
        });
        jMenu2.add(Menu_eliminarAlbum);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_insertRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_insertRecordActionPerformed
        try {
            // TODO add your handling code here:
            System.out.println(Text_idAlbum.getText());
            System.out.println(Text_idInterprete.getText());
            System.out.println(Text_nameAlbum.getText());
            System.out.println(Text_lugarGrabacion.getText());
            System.out.println(Text_anioLan.getText());
            backEnd_album.insertAlbum(Integer.parseInt(Text_idAlbum.getText()), Integer.parseInt(Text_idInterprete.getText()), Text_nameAlbum.getText(), Text_lugarGrabacion.getText(), Text_anioLan.getText());
            
        } catch (SQLException ex) {
            Logger.getLogger(interfazAlbum.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(interfazAlbum.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Button_insertRecordActionPerformed

    private void Button_clearCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_clearCamposActionPerformed
        // TODO add your handling code here:
        Text_idAlbum.setText("");
        Text_idInterprete.setText("");
        Text_nameAlbum.setText("");
        Text_lugarGrabacion.setText("");
        Text_anioLan.setText("");
    }//GEN-LAST:event_Button_clearCamposActionPerformed

    private void Button_showDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_showDataActionPerformed
        try {
            // TODO add your handling code here:
            backEnd_album.MostrarDataAlbum(Table_dataAlbum);
        } catch (SQLException ex) {
            Logger.getLogger(interfazAlbum.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Button_showDataActionPerformed

    private void Button_deleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_deleteRecordActionPerformed
        try {
            // TODO add your handling code here:            
            backEnd_album.deleteAlbum(CB_options.getItemAt(CB_options.getSelectedIndex()), Text_input.getText());
        } catch (SQLException ex) {
            Logger.getLogger(interfazAlbum.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_Button_deleteRecordActionPerformed

    private void Button_searchRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_searchRecordActionPerformed
        try {
            // TODO add your handling code here:

            backEnd_album.buscarAlbum(CB_options.getItemAt(CB_options.getSelectedIndex()), Table_dataAlbum, Text_input.getText());
        } catch (SQLException ex) {
            Logger.getLogger(interfazAlbum.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Button_searchRecordActionPerformed

    private void Table_dataAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_dataAlbumMouseClicked
        // TODO add your handling code here:
        Button_insertRecord.setVisible(false);
        Button_clearCampos.setVisible(false);
        Button_showData.setVisible(true);
        Button_deleteRecord.setVisible(false);
        Button_searchRecord.setVisible(false);
        Button_updateRecord.setVisible(true);
        //combo
        CB_options.setVisible(true);
        //tabla
        Table_dataAlbum.setVisible(true);
        //textfield
        Text_anioLan.setEnabled(true);
        Text_idAlbum.setEnabled(false);
        Text_idInterprete.setEnabled(false);
        Text_input.setVisible(true);
        Text_lugarGrabacion.setEnabled(true);
        Text_nameAlbum.setEnabled(true);
        if (evt.getClickCount()==2) {
            for (int i = 0; i < Table_dataAlbum.getRowCount(); i++) {
                Text_idAlbum.setText(Table_dataAlbum.getValueAt(i, 0).toString());
                Text_idInterprete.setText(Table_dataAlbum.getValueAt(i, 1).toString());
                Text_nameAlbum.setText(Table_dataAlbum.getValueAt(i, 2).toString());
                Text_lugarGrabacion.setText(Table_dataAlbum.getValueAt(i, 3).toString());
                Text_anioLan.setText(Table_dataAlbum.getValueAt(i, 4).toString());            
            }
        }
    }//GEN-LAST:event_Table_dataAlbumMouseClicked

    private void Button_updateRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_updateRecordActionPerformed
        try {
            // TODO add your handling code here:
            backEnd_album.updateAlbum(CB_options.getItemAt(CB_options.getSelectedIndex()), Text_input.getText(), Text_nameAlbum.getText(), Text_lugarGrabacion.getText(), Text_anioLan.getText());
        } catch (SQLException ex) {
            Logger.getLogger(interfazAlbum.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Button_updateRecordActionPerformed

    private void Menu_nuevoAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_nuevoAlbumActionPerformed
        // TODO add your handling code here:
        Text_anioLan.setText("");
        Text_idAlbum.setText("");
        Text_idInterprete.setText("");
        Text_input.setText("");
        Text_lugarGrabacion.setText("");
        Text_nameAlbum.setText("");
        //botones
        Button_insertRecord.setVisible(true);
        Button_clearCampos.setVisible(true);
        Button_showData.setVisible(true);
        Button_deleteRecord.setVisible(false);
        Button_searchRecord.setVisible(false);
        Button_updateRecord.setVisible(false);
        //combo
        CB_options.setVisible(false);
        //tabla
        Table_dataAlbum.setVisible(true);
        //textfield
        Text_anioLan.setEnabled(true);
        Text_idAlbum.setEnabled(true);
        Text_idInterprete.setEnabled(true);        
        Text_input.setVisible(false);
        Text_lugarGrabacion.setEnabled(true);
        Text_nameAlbum.setEnabled(true);
    }//GEN-LAST:event_Menu_nuevoAlbumActionPerformed

    private void Menu_buscarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_buscarAlbumActionPerformed
        // TODO add your handling code here:
        Text_anioLan.setText("");
        Text_idAlbum.setText("");
        Text_idInterprete.setText("");
        Text_input.setText("");
        Text_lugarGrabacion.setText("");
        Text_nameAlbum.setText("");
        //botones
        Button_insertRecord.setVisible(false);
        Button_clearCampos.setVisible(false);
        Button_showData.setVisible(false);
        Button_deleteRecord.setVisible(false);
        Button_searchRecord.setVisible(true);
        Button_updateRecord.setVisible(false);
        //combo
        CB_options.setVisible(true);
        //tabla
        Table_dataAlbum.setVisible(true);
        //textfield
        Text_anioLan.setEnabled(false);
        Text_idAlbum.setEnabled(false);
        Text_idInterprete.setEnabled(false);
        Text_input.setVisible(true);
        Text_lugarGrabacion.setEnabled(false);
        Text_nameAlbum.setEnabled(false);
    }//GEN-LAST:event_Menu_buscarAlbumActionPerformed

    private void Menu_eliminarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_eliminarAlbumActionPerformed
        // TODO add your handling code here:
        Text_anioLan.setText("");
        Text_idAlbum.setText("");
        Text_idInterprete.setText("");
        Text_input.setText("");
        Text_lugarGrabacion.setText("");
        Text_nameAlbum.setText("");
        //botones
        Button_insertRecord.setVisible(false);
        Button_clearCampos.setVisible(false);
        Button_showData.setVisible(true);
        Button_deleteRecord.setVisible(true);
        Button_searchRecord.setVisible(false);
        Button_updateRecord.setVisible(false);
        //combo
        CB_options.setVisible(true);
        //tabla
        Table_dataAlbum.setVisible(true);
        //textfield
        Text_anioLan.setEnabled(false);
        Text_idAlbum.setEnabled(false);
        Text_idInterprete.setEnabled(false);
        Text_input.setVisible(true);
        Text_lugarGrabacion.setEnabled(false);
        Text_nameAlbum.setEnabled(false);
    }//GEN-LAST:event_Menu_eliminarAlbumActionPerformed

    private void btn_regresarMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarMainActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new interfazPrincipal().setVisible(true);
    }//GEN-LAST:event_btn_regresarMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazAlbum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_clearCampos;
    private javax.swing.JButton Button_deleteRecord;
    private javax.swing.JButton Button_insertRecord;
    private javax.swing.JButton Button_searchRecord;
    private javax.swing.JButton Button_showData;
    private javax.swing.JButton Button_updateRecord;
    private javax.swing.JComboBox<String> CB_options;
    private javax.swing.JMenuItem Menu_buscarAlbum;
    private javax.swing.JMenuItem Menu_eliminarAlbum;
    private javax.swing.JMenuItem Menu_nuevoAlbum;
    private javax.swing.JTable Table_dataAlbum;
    private javax.swing.JTextField Text_anioLan;
    private javax.swing.JTextField Text_idAlbum;
    private javax.swing.JTextField Text_idInterprete;
    private javax.swing.JTextField Text_input;
    private javax.swing.JTextField Text_lugarGrabacion;
    private javax.swing.JTextField Text_nameAlbum;
    private javax.swing.JButton btn_regresarMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
