/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import RedBayesiana.FutbolRed;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.openmarkov.core.exception.IncompatibleEvidenceException;
import org.openmarkov.core.exception.InvalidStateException;
import org.openmarkov.core.exception.NotEvaluableNetworkException;
import org.openmarkov.core.exception.ParserException;
import org.openmarkov.core.exception.ProbNodeNotFoundException;
import org.openmarkov.core.exception.UnexpectedInferenceException;

import DatosEquipos.DatosDeLosEquipos;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.openmarkov.core.exception.NodeNotFoundException;

/**
 *
 * @author Katty
 */
public class VentanaDeDatos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaDeDatos
     */
    //FutbolRed red1;
    DatosDeLosEquipos datos ;
    
    public VentanaDeDatos() {
        initComponents();
        //red1 = new FutbolRed("C:\\Users\\JeKa\\Documents\\POLI\\QUINTO SEMESTRE\\Inteligencia Artificial\\PrediccionFutbol_RB\\redBayesianaFutbol.pgmx");
        datos = new DatosDeLosEquipos();
    }
    //FutbolRed 
    
     
   public DefaultTableModel tablaModelo(JTable table) {

        DefaultTableModel modelo = (DefaultTableModel) table.getModel();
        table.setModel(modelo);
        return modelo;
    }

    public void llenarTablaProbabilidad(DefaultTableModel modelo, FutbolRed red) {
        int n=10;
        int m=2;
        
        String[] titulo = {"VARIABLE:", "PROBABILIDAD"};
        String []objecto=new String[m];

        objecto[0]="Pronostico";
        objecto[1]=red.getResultado();
        modelo.addRow(objecto);
        objecto[0]="Motivacion Local";
        
        objecto[1]=red.getResultado1();
        modelo.addRow(objecto);
        objecto[0]="Motivacion Visitante";
        objecto[1]=red.getResultado2();
        modelo.addRow(objecto);
         objecto[0]="jugada Local";
        objecto[1]=red.getResultado3();
        modelo.addRow(objecto);
         objecto[0]="Jugada Visitante";
        objecto[1]=red.getResultado4();
        modelo.addRow(objecto);
        
      
    }

    public void limpiarTabla(JTable tabla) {

        while (tabla.getRowCount() > 0) {

            ((DefaultTableModel) tabla.getModel()).removeRow(0);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CB_estacion = new javax.swing.JComboBox<>();
        CB_clasico = new javax.swing.JComboBox<>();
        CB_lleno = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        CB_arbitro = new javax.swing.JComboBox<>();
        CB_resultadosHistoricos = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        TX_plantillaLocal = new javax.swing.JTextField();
        CB_rachaLocal = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        CB_partidosHistoricosLocal = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        CB_sistemaTacticoLocal = new javax.swing.JComboBox<>();
        TX_presupuestoLocal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        TX_plantillaV = new javax.swing.JTextField();
        CB_tacticaV = new javax.swing.JComboBox<>();
        CB_rachaV = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        CB_historicosV = new javax.swing.JComboBox<>();
        CB_distancia = new javax.swing.JComboBox<>();
        CB_transporte = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TX_presupuestoV = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        cbox_Estado = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProba = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane4.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jTabbedPane4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane4MouseClicked(evt);
            }
        });

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setText("SEASON");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(210, 70, 180, 20);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel10.setText("IS IT A CLASSIC?");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(220, 210, 150, 20);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel12.setText("FULL STADIUM");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(210, 160, 140, 20);

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel13.setText("HISTORICAL RESULTS");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(210, 260, 220, 20);

        CB_estacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "verano", "otonio", "invierno", "primavera" }));
        jPanel2.add(CB_estacion);
        CB_estacion.setBounds(410, 70, 90, 30);

        CB_clasico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no", "si" }));
        jPanel2.add(CB_clasico);
        CB_clasico.setBounds(410, 200, 50, 30);

        CB_lleno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no", "si" }));
        jPanel2.add(CB_lleno);
        CB_lleno.setBounds(410, 150, 60, 30);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("REFEREE");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(210, 120, 180, 20);

        CB_arbitro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bueno", "malo" }));
        jPanel2.add(CB_arbitro);
        CB_arbitro.setBounds(410, 110, 90, 30);

        CB_resultadosHistoricos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "victorias", "empates", "derrotas" }));
        CB_resultadosHistoricos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_resultadosHistoricosActionPerformed(evt);
            }
        });
        jPanel2.add(CB_resultadosHistoricos);
        CB_resultadosHistoricos.setBounds(470, 260, 110, 30);

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(0, 20, 840, 540);

        jTabbedPane4.addTab("General Data", jPanel2);

        jTabbedPane5.setPreferredSize(new java.awt.Dimension(600, 600));
        jTabbedPane5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane5MouseClicked(evt);
            }
        });

        jPanel4.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel15.setText("Number of Players ");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(100, 110, 310, 30);

        jLabel21.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel21.setText("Tactical System");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(120, 190, 230, 30);

        jLabel26.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel26.setText("Is it in streak?");
        jPanel4.add(jLabel26);
        jLabel26.setBounds(90, 150, 240, 30);

        TX_plantillaLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TX_plantillaLocalActionPerformed(evt);
            }
        });
        jPanel4.add(TX_plantillaLocal);
        TX_plantillaLocal.setBounds(400, 110, 60, 30);

        CB_rachaLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no", "si" }));
        jPanel4.add(CB_rachaLocal);
        CB_rachaLocal.setBounds(400, 150, 40, 30);

        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel24.setText("Historical Results");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(180, 230, 260, 30);

        CB_partidosHistoricosLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "derrotas", "empates", "victorias" }));
        jPanel4.add(CB_partidosHistoricosLocal);
        CB_partidosHistoricosLocal.setBounds(400, 230, 70, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Information of Team");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(230, 20, 240, 28);

        CB_sistemaTacticoLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "otro sistema", "4 2 3 1", "4 3 3", "4 4 2" }));
        jPanel4.add(CB_sistemaTacticoLocal);
        CB_sistemaTacticoLocal.setBounds(400, 190, 120, 30);
        jPanel4.add(TX_presupuestoLocal);
        TX_presupuestoLocal.setBounds(400, 70, 70, 30);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setText("BUDGET $ (millons)");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(140, 70, 280, 30);
        jPanel4.add(jLabel14);
        jLabel14.setBounds(-20, 10, 620, 460);

        jTabbedPane5.addTab("Local Team: ", jPanel4);

        jPanel5.setLayout(null);

        jLabel29.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel29.setText("Number of Players");
        jPanel5.add(jLabel29);
        jLabel29.setBounds(20, 230, 280, 21);

        jLabel36.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel36.setText("Tactical System");
        jPanel5.add(jLabel36);
        jLabel36.setBounds(20, 280, 210, 21);

        jLabel38.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel38.setText("Is it in streak?");
        jPanel5.add(jLabel38);
        jLabel38.setBounds(20, 320, 160, 21);
        jPanel5.add(TX_plantillaV);
        TX_plantillaV.setBounds(290, 230, 80, 30);

        CB_tacticaV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "otro sistema", "4 2 3 1", "4 3 3", "4 4 2" }));
        jPanel5.add(CB_tacticaV);
        CB_tacticaV.setBounds(290, 270, 110, 30);

        CB_rachaV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no", "si" }));
        jPanel5.add(CB_rachaV);
        CB_rachaV.setBounds(290, 310, 70, 30);

        jLabel42.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel42.setText("Historical Results");
        jPanel5.add(jLabel42);
        jLabel42.setBounds(20, 360, 240, 21);

        CB_historicosV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "derrotas", "empates", "victorias" }));
        jPanel5.add(CB_historicosV);
        CB_historicosV.setBounds(290, 350, 80, 30);

        CB_distancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "corta", "media", "larga" }));
        jPanel5.add(CB_distancia);
        CB_distancia.setBounds(50, 100, 100, 40);

        CB_transporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bus", "Avion" }));
        jPanel5.add(CB_transporte);
        CB_transporte.setBounds(310, 100, 80, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("TRIP");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(220, 30, 60, 28);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setText("Distance");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(20, 70, 250, 21);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setText("Transportation");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(270, 70, 230, 21);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Information of Team");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(20, 150, 220, 28);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setText("BUDGET $ (millons)");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(20, 190, 250, 21);
        jPanel5.add(TX_presupuestoV);
        TX_presupuestoV.setBounds(290, 190, 80, 30);
        jPanel5.add(jLabel16);
        jLabel16.setBounds(0, 0, 610, 530);

        jTabbedPane5.addTab("Visiting Team", jPanel5);

        jTabbedPane4.addTab("Team's Data", jTabbedPane5);

        jPanel6.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 51));
        jButton1.setText("Forecast");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);
        jButton1.setBounds(360, 90, 189, 59);

        cbox_Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Que Gane Local", "EMPATE", "Que Gane Visitante" }));
        jPanel6.add(cbox_Estado);
        cbox_Estado.setBounds(60, 100, 165, 48);

        jLabel44.setFont(new java.awt.Font("Times New Roman", 3, 28)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(204, 0, 51));
        jLabel44.setText("WHAT DO YOU WANT TO PREDICT?");
        jPanel6.add(jLabel44);
        jLabel44.setBounds(40, 30, 550, 33);

        tableProba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "VARIABLE", "PROBABILIDAD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableProba);

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(90, 240, 452, 142);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField2);
        jTextField2.setBounds(50, 160, 510, 52);
        jPanel6.add(jLabel17);
        jLabel17.setBounds(0, 60, 590, 460);

        jTabbedPane4.addTab("Forecast", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    FutbolRed red1 = new FutbolRed("C:\\Users\\KEVIN\\Google Drive\\Artificial\\redBayesianaFutbol.pgmx");
    //DatosDeLosEquipos datos = new DatosDeLosEquipos();
//        int opcion;
        try {
            String estado = datos.EstadosDeciados(cbox_Estado.getItemAt(cbox_Estado.getSelectedIndex()));
            //--------------------------datos generales
            String estacion = CB_estacion.getItemAt(CB_estacion.getSelectedIndex());
            String arbitro = CB_arbitro.getItemAt(CB_arbitro.getSelectedIndex());
            String clasico = CB_clasico.getItemAt(CB_clasico.getSelectedIndex());
            String lleno = CB_lleno.getItemAt(CB_lleno.getSelectedIndex());
            String resultados = CB_resultadosHistoricos.getItemAt(CB_resultadosHistoricos.getSelectedIndex());

            //------------------------local
            String moneyLocal = datos.Presupuesto(TX_presupuestoLocal.getText());
            String plantillaLocal = datos.Plantilla(TX_plantillaLocal.getText());
            String sistemaLocal = datos.SistemaTactico(CB_sistemaTacticoLocal.getItemAt(CB_sistemaTacticoLocal.getSelectedIndex()));
            String rachaLocal = CB_rachaLocal.getItemAt(CB_rachaLocal.getSelectedIndex());
            String partidosHistoricoL = CB_partidosHistoricosLocal.getItemAt(CB_partidosHistoricosLocal.getSelectedIndex());

            // datos visitante
            String viaje = CB_distancia.getItemAt(CB_distancia.getSelectedIndex()) + CB_transporte.getItemAt(CB_transporte.getSelectedIndex());
            String moneyV = datos.Presupuesto(TX_presupuestoV.getText());
            String plantillaV = datos.Plantilla(TX_plantillaV.getText());
            String sistemaV = datos.SistemaTactico(CB_tacticaV.getItemAt(CB_tacticaV.getSelectedIndex()));
            String rachaV = CB_rachaV.getItemAt(CB_rachaV.getSelectedIndex());
            String historiaV = CB_historicosV.getItemAt(CB_historicosV.getSelectedIndex());

            red1.pronosticoGanaLocal(estado, estacion, arbitro, clasico, lleno, resultados,
                    moneyLocal, plantillaLocal, sistemaLocal, rachaLocal, partidosHistoricoL,
                    viaje, moneyV, plantillaV, sistemaV, rachaV, historiaV);

////            opcion = JOptionPane.showConfirmDialog(null, "La probabilidad de " + cbox_Estado.getItemAt(cbox_Estado.getSelectedIndex()) + "\n Es " + red.getResultado(), "Continuar ?", JOptionPane.YES_OPTION);
////            if (opcion == 1) {
////                System.exit(0);
                jTextField2.setText("La probabilidad de " + cbox_Estado.getItemAt(cbox_Estado.getSelectedIndex()) + "\n Es " + red1.getResultado());
//            }
               limpiarTabla(tableProba);
              llenarTablaProbabilidad(tablaModelo(tableProba),red1 );
               

        } catch (ParserException ex) {
            Logger.getLogger(VentanaDeDatos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VentanaDeDatos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotEvaluableNetworkException ex) {
            Logger.getLogger(VentanaDeDatos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ProbNodeNotFoundException ex) {
            Logger.getLogger(VentanaDeDatos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IncompatibleEvidenceException ex) {
            Logger.getLogger(VentanaDeDatos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnexpectedInferenceException ex) {
            Logger.getLogger(VentanaDeDatos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidStateException ex) {
            Logger.getLogger(VentanaDeDatos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NodeNotFoundException ex) {
            Logger.getLogger(VentanaDeDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTabbedPane4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane4MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTabbedPane4MouseClicked

    private void jTabbedPane5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane5MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTabbedPane5MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void TX_plantillaLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TX_plantillaLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TX_plantillaLocalActionPerformed

    private void CB_resultadosHistoricosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_resultadosHistoricosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_resultadosHistoricosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VentanaDeDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_arbitro;
    private javax.swing.JComboBox<String> CB_clasico;
    private javax.swing.JComboBox<String> CB_distancia;
    private javax.swing.JComboBox<String> CB_estacion;
    private javax.swing.JComboBox<String> CB_historicosV;
    private javax.swing.JComboBox<String> CB_lleno;
    private javax.swing.JComboBox<String> CB_partidosHistoricosLocal;
    private javax.swing.JComboBox<String> CB_rachaLocal;
    private javax.swing.JComboBox<String> CB_rachaV;
    private javax.swing.JComboBox<String> CB_resultadosHistoricos;
    private javax.swing.JComboBox<String> CB_sistemaTacticoLocal;
    private javax.swing.JComboBox<String> CB_tacticaV;
    private javax.swing.JComboBox<String> CB_transporte;
    private javax.swing.JTextField TX_plantillaLocal;
    private javax.swing.JTextField TX_plantillaV;
    private javax.swing.JTextField TX_presupuestoLocal;
    private javax.swing.JTextField TX_presupuestoV;
    private javax.swing.JComboBox<String> cbox_Estado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tableProba;
    // End of variables declaration//GEN-END:variables

}
